language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

dist: xenial
sudo: true

install:
  # needed by pysodium
  - sudo apt-get install libsodium18
  # install poetry
  - make get-poetry
  # activate poetry command
  - source $HOME/.poetry/env
  # install project
  - make install

script:
  - make build

after_success:
  # publish code coverage statistics
  coveralls
