[tool.poetry]
name = "python-paseto"
version = "0.1.0"
description = "Platform-Agnostic Security Tokens for Python"
authors = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
pynacl = "^1.3"
pysodium = "^0.7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.9"
black = "^18.3-alpha.0"
pylama = "^7.6"
tox = "^3.5"
coverage = "^4.5"
mypy = "^0.641.0"
coveralls = "^1.5"

[tool.black]
exclude = '/(submodules|.tox)/'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
