name: ci-workflow
# run workflow for these events
on: [push, pull_request, workflow_dispatch]

jobs:
  # define build job
  build:
    # type of machine
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
        os: ['ubuntu-20.04', 'macos-10.15', 'windows-2019']
        include:
          - os: ['ubuntu-20.04', 'macos-10.15']
            poetry-path: ['$HOME/.poetry/bin']
          - os: ['windows-2019']
            poetry-path: ['%USERPROFILE%\.poetry\bin']
      fail-fast: false
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: make get-poetry
      - name: Enable poetry command
        run: echo "${{ matrix.poetry-path }}" >> $GITHUB_PATH
      - name: Configure poetry
        run: poetry config virtualenvs.create false # disable creating virtual environment
      - name: Install dependencies
        run: make install
      - name: Check code formatting
        run: black --check .
      - name: Lint code
        run: make lint
      - name: Run tests with code coverage
        run: make coverage
